### ISSUE TITLE
build error MSB8024: Using static version of the C++ runtime library is not supported

### ISSUE THREAD

**Issue by sggeng** [Microsoft/openssl#11]
try to build NT-Store-8.1-Static-Unicode-winrtcomponent as static library (I set the C++ runtime library  to /MT) from VS2013. 

Got the following error:
MSB8024: Using static version of the C++ runtime library is not supported

How to build openssl as a static library for windows store apps?

**Comment by khouzam** [comment]
The winrtcomponent projects are only there for the testing application. 

You only need to include the output of NT-Store-8.1-Static-Unicode in your actual application. Those are the openSSL static libraries. Your application will still need to link with the dynamic version of the runtime since that's a store policy but openSSL will be statically linked into your app.
