### ISSUE TITLE
Compile OpenSSL for WP8.0

### ISSUE THREAD

**Issue by skiner** [Microsoft/openssl#12]
I cant to add compiled dll into my WP8.0 project, i always get error "A reference to a higher version or incompatible assembly cannot be added to the project."

How i do it:
1. Execute the following script in the source root tree.
   ms\do_vsprojects.bat
2. Open visual studio solution created
   vsout\openssl.sln
3. Run Unit Test App Projects
4. ms\do_packwinapp.bat

Finally i got two dlls ssleay32.dll and libeay32.dll from path "\openssl\vsout\package\bin\Phone\8.0\Dll\Unicode\Release\arm". I am trying to add this dlls into my WP8.0 project.

What am i doing wrong?
Thanks.

**Comment by khouzam** [comment]
Hi Skiner,

You are doing the right steps to produce the DLLs. However, these are native C++ DLLs and not managed DLLs.. In order to use them in a C# project you will need to have a WinRT C++ component that can act as the bridge. That component would produce a .WinMD file which can be consumed by C# and it would link with ssleay.lib and libeay.lib and expose their functionality. This is similar to how the test application is written. It is a C# application, invoking the WinRT C++ test component that calls into OpenSSL to run the test suite.

This can give you more details about it:
https://msdn.microsoft.com/en-us/library/windows/apps/hh441569(v=vs.110).aspx
