### ISSUE TITLE
OpenSSL 1.0.2n

### ISSUE THREAD

**Issue by wangdevmgit** [Microsoft/openssl#50]
Hi, is there any plan to bump OpenSSL 1.0.2m to 1.0.2n?

**Comment by khouzam** [comment]
Yes, I will do that this week.

**Comment by wangdevmgit** [comment]
Thanks! @khouzam

**Comment by khouzam** [comment]
Done. The code has been updated to 1.0.2n.

Use the tag: OpenSSL_1_0_2n_WinRT

**Comment by noloader** [comment]
@khouzam,

A quick heads up...

TLS 1.3 is in Last Call (LC) at the TLS Working Group (WG). See, for example, [Genart last call review of draft-ietf-tls-tls13-24](https://www.ietf.org/mail-archive/web/tls/current/msg25533.html). It should publish soon.

TLS 1.3 will have a lot of goodies, like new x25519 key exchange, ChaCha and Poly1305. OpenSSL 1.1 is required for TLS 1.3. It is not present in OpenSSL 1.0.2.

OpenSSL 1.1 is not binary compatible with OpenSSL 1.0.2. OpenSSL 1.1 breaks a lot of builds due to the incompatibilities.
